version: '3.8'
services:
  products-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dp_user
      - POSTGRES_PASSWORD=dp_password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dp_user" ]
      interval: 15s
      timeout: 15s
      retries: 50

  product-migrations:
    build:
      context: ../../product-migrations/
      dockerfile: local.Dockerfile
    container_name: product-migrations
    depends_on:
      products-db:
        condition: service_healthy

  products:
    build:
      context: ../../products/
      dockerfile: local.Dockerfile
    container_name: products
    ports:
      - 5555:5555 # api port
      - 2346:2346 # debug port
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../products/:/products

volumes:
  db:
    driver: local
    ## We want the Redis data not to persist. 
    ## Commenting out the lines below is equivalent to run the command FLUSHALL after each restart
    ## Uncomment the following lines to persist data
    # redis:
    #   driver: local
